### ISSUE TITLE
ORM reference inside domain layer

### ISSUE THREAD

**Issue by ye7iaserag** [aat2703/hexagonal-architecture#4]
Shouldn't ORM entity remain in infrastructure while using pure domain entities inside domain?

I've noticed that the domain is coupled with doctrine which goes against DDD

Care to elaborate your choice?

**Comment by aat2703** [comment]
You're right! entities / aggregates should know nothing about how it is persisted. But remember DDD is a mindset, not a religion!

This is one of the tradeoffs of using an ORM. I could of course have used yml, xml, annotations or php attributes. All of those solutions would also couple me to Doctrine, even though it's not visible in the entities (at some point it will using Doctrine Collections e.g one-to-many relationships)

[Here](https://github.com/aat2703/hexagonal-architecture-csharp/blob/master/src/HexagonalArchitecture.Api/Infrastructure/Persistence/Context/ShopDbContext.cs) is an example in .NET where i reference the entities in the infrastructure layer and determine how it maps to the database. 

Another option is raw SQL using PDO. This is especially preferred when hydrating read models. 

I hope i make sense :-)

**Comment by ye7iaserag** [comment]
got your point, really thankful for your explanation
